name: Auto Reels WP→FB+IG

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"  # a cada 30 min (UTC)

concurrency:
  group: auto-reels
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 40          # limite geral do job

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install system deps (ffmpeg)
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env from Secrets
        run: |
          cat > .env << 'EOF'
          USER_ACCESS_TOKEN=${{ secrets.USER_ACCESS_TOKEN }}
          FACEBOOK_PAGE_ID=${{ secrets.FACEBOOK_PAGE_ID }}
          INSTAGRAM_ID=${{ secrets.INSTAGRAM_ID }}
          API_VERSION=v23.0
          EOF

      - name: Quick connectivity check (WP API)
        run: |
          set -eux
          curl -sS -I "https://jornalvozdolitoral.com/wp-json/wp/v2/posts?per_page=1" | cat

      # Roda o script com timeout de 20 minutos e saída sem buffer (-u)
      # Se travar (ex.: polling do IG), o step termina e o job segue.
      - name: Run auto_reels once (with timeout)
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          set -eux
          mkdir -p out
          # timeouts defensivos: 20min
          timeout 20m python -u auto_reels_wp_publish.py

      - name: Upload out/ as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: out-${{ github.run_id }}
          path: out/
          if-no-files-found: warn
