name: Auto Reels WP→FB+IG

on:
  schedule:
    - cron: "*/5 * * * *"   # roda a cada 10 minutos
  workflow_dispatch:         # permite rodar manualmente

concurrency:
  group: auto-reels
  cancel-in-progress: false

jobs:
  run-once:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run script (single pass)
        env:
          RUN_ONCE: "1"
          WP_URL: ${{ secrets.WP_URL }}
          USER_ACCESS_TOKEN: ${{ secrets.USER_ACCESS_TOKEN }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
          INSTAGRAM_ID: ${{ secrets.INSTAGRAM_ID }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
        run: python auto_reels_wp_publish.py
