name: Auto Reels WP→FB+IG

on:
  # dispara manualmente quando quiser
  workflow_dispatch:
  # roda AUTOMÁTICO a cada 30 minutos (UTC)
  schedule:
    - cron: "*/30 * * * *"

# evita duas execuções simultâneas
concurrency:
  group: auto-reels
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 50  # margem segura < 60min por execução

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install system deps (ffmpeg)
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env from GitHub Secrets
        run: |
          cat > .env << 'EOF'
          USER_ACCESS_TOKEN=${{ secrets.USER_ACCESS_TOKEN }}
          FACEBOOK_PAGE_ID=${{ secrets.FACEBOOK_PAGE_ID }}
          INSTAGRAM_ID=${{ secrets.INSTAGRAM_ID }}
          API_VERSION=v23.0
          EOF

      - name: Run once (buscar posts → gerar arte/vídeo → publicar)
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          python auto_reels_wp_publish.py

      # (Opcional) guarda os últimos arquivos gerados para você baixar pelos Logs/Artifacts
      - name: Upload out/
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: out-${{ github.run_id }}
          path: out/
          if-no-files-found: ignore
