name: Auto Reels WP→FB+IG

on:
  workflow_dispatch:        # permite rodar manualmente
  schedule:
    - cron: "*/15 * * * *"  # roda a cada 10 minutos (24/7)

permissions:
  contents: read

concurrency:
  group: auto-reels-wp      # evita sobreposição
  cancel-in-progress: true

jobs:
  run-once:
    runs-on: ubuntu-latest
    timeout-minutes: 12     # se travar, mata em 12 min (economiza minutos)
    env:
      # --- seus segredos (já cadastrados em Settings > Secrets and variables > Actions) ---
      WP_URL: ${{ secrets.WP_URL }}
      USER_ACCESS_TOKEN: ${{ secrets.USER_ACCESS_TOKEN }}
      FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
      INSTAGRAM_ID: ${{ secrets.INSTAGRAM_ID }}

      # ajustes rápidos (se quiser sobrepor os defaults do script)
      VIDEO_SECONDS: "10"
      WP_POSTS: "5"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        run: |
          echo "Starting..."
          python auto_reels_wp_publish.py
